[project]
name = "kali"
version = "0.1.0"
description = "Exploring polars"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.35.2",
]

[tool.ruff]
lint.select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # Pylint
    "PL"
]
lint.ignore = [
    # tests use assert
    "S101"
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]
